apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: mynodeapp:latest
        ports:
        - containerPort: 3000
